"""
Generate 2D sinusoidal positional encodings for image-like inputs.

This layer implements the 2D sinusoidal positional encoding scheme, a critical
component for injecting spatial awareness into attention-based models like
Vision Transformers. Self-attention mechanisms are permutation-equivariant and
lack any inherent understanding of the spatial arrangement of input tokens (e.g.,
image patches or feature map pixels). This layer provides a fixed, non-learnable
encoding that gives the model a unique signal for each absolute position in the
2D grid.

Architecture and Foundational Mathematics:
The method is a direct two-dimensional extension of the 1D positional
encodings introduced in the original Transformer model. The core idea is to
use sine and cosine functions of varying frequencies to create a unique vector
for each position.

For a 2D feature map of shape `(H, W)`, the encoding is generated by
independently creating positional vectors for the y-axis (height) and the
x-axis (width) and then concatenating them.

For any given position `pos` along a single axis (either x or y) and a
given channel index `i` in the embedding space, the encoding is calculated
as:

    PE(pos, 2i)   = sin(pos / T^(2i / d))
    PE(pos, 2i+1) = cos(pos / T^(2i / d))

Where:
- `pos` is the integer coordinate (e.g., 0, 1, 2, ...).
- `d` is the dimensionality of the positional encoding for a single axis
  (`num_pos_feats`).
- `i` is the dimension index, `0 <= i < d/2`.
- `T` is a large constant `temperature` (e.g., 10000).

The wavelengths of the sinusoids form a geometric progression, from `2π` to
`2π * T`. This allows the model to represent positions as a combination of
signals at different frequencies. A key intuition is that this formulation
enables the model to easily learn relative positions. Due to trigonometric
identities, for any fixed offset `k`, `PE(pos + k)` can be represented as a
linear transformation of `PE(pos)`, making it simple for the attention
mechanism to learn how to attend to relative spatial locations.

The final output for a spatial location `(y, x)` is the channel-wise
concatenation of the y-encoding and the x-encoding, resulting in a feature
dimension of `2 * d`.

References:
  - "Attention Is All You Need" (Vaswani et al., 2017)
    https://arxiv.org/abs/1706.03762
  - "End-to-End Object Detection with Transformers" (Carion et al., 2020)
    https://arxiv.org/abs/2005.12872

"""

import math
import keras
from keras import ops
from typing import Optional, Dict, Any, Tuple

# ---------------------------------------------------------------------

@keras.saving.register_keras_serializable()
class PositionEmbeddingSine2D(keras.layers.Layer):
    """Fixed 2D sinusoidal positional encoding for image-like feature maps.

    Generates non-learnable positional encodings using sine and cosine functions
    of varying frequencies along both spatial axes independently. For a feature
    map of shape ``(H, W)``, coordinate grids are created for both axes,
    optionally normalized, and then encoded via
    ``PE(pos, 2i) = sin(pos / T^(2i/d))`` and
    ``PE(pos, 2i+1) = cos(pos / T^(2i/d))``, where ``T`` is the temperature
    and ``d = num_pos_feats``. The y-axis and x-axis encodings are concatenated
    to produce the final output of dimension ``2 * num_pos_feats``.

    **Architecture Overview:**

    .. code-block:: text

        ┌──────────────────────────────────────┐
        │  Input (batch, H, W, C)              │
        └───────────────┬──────────────────────┘
                        ▼
        ┌──────────────────────────────────────┐
        │  Generate Y / X coordinate grids     │
        │  via cumulative sum over mask        │
        └──────┬────────────────┬──────────────┘
               ▼                ▼
        ┌──────────────┐ ┌──────────────┐
        │  Normalize Y │ │  Normalize X │
        │  (optional)  │ │  (optional)  │
        └──────┬───────┘ └──────┬───────┘
               ▼                ▼
        ┌──────────────┐ ┌──────────────┐
        │  sin/cos(Y)  │ │  sin/cos(X)  │
        │  → d feats   │ │  → d feats   │
        └──────┬───────┘ └──────┬───────┘
               └───────┬────────┘
                       ▼
        ┌──────────────────────────────────────┐
        │  Concatenate → (batch, 2d, H, W)     │
        └──────────────────────────────────────┘

    :param num_pos_feats: Number of features for the positional encoding,
        corresponding to half the channel dimension of the final encoding.
        Defaults to ``64``.
    :type num_pos_feats: int
    :param temperature: Temperature value that controls the frequency of the
        sine and cosine functions. Defaults to ``10000.0``.
    :type temperature: float
    :param normalize: If ``True``, normalizes the positional encodings by the
        spatial dimensions before applying trigonometric functions. Defaults
        to ``True``.
    :type normalize: bool
    :param scale: Scaling factor for the normalized positional encodings. Only
        used if ``normalize`` is ``True``. Defaults to ``2 * pi``.
    :type scale: float
    :param kwargs: Additional arguments for the Layer base class.
    """

    def __init__(
        self,
        num_pos_feats: int = 64,
        temperature: float = 10000.0,
        normalize: bool = True,
        scale: float = 2 * math.pi,
        **kwargs: Any
    ):
        super().__init__(**kwargs)

        # Validate inputs
        if num_pos_feats <= 0:
            raise ValueError(f"num_pos_feats must be positive, got {num_pos_feats}")
        if temperature <= 0:
            raise ValueError(f"temperature must be positive, got {temperature}")

        # Store configuration
        self.num_pos_feats = num_pos_feats
        self.temperature = temperature
        self.normalize = normalize
        self.scale = scale

    def call(self, inputs: keras.KerasTensor, mask: Optional[keras.KerasTensor] = None) -> keras.KerasTensor:
        """Generate 2D sinusoidal positional encodings for the input feature map.

        :param inputs: Input tensor of shape ``(batch, H, W, C)``.
        :type inputs: keras.KerasTensor
        :param mask: Optional boolean mask of shape ``(batch, H, W)``. Positions
            where the mask is ``True`` are treated as padding.
        :type mask: Optional[keras.KerasTensor]
        :return: Positional encoding tensor of shape
            ``(batch, 2 * num_pos_feats, H, W)``.
        :rtype: keras.KerasTensor
        """
        if mask is None:
            # Assumes a 4D input (B, H, W, C), mask should be (B, H, W)
            mask = ops.zeros(ops.shape(inputs)[:3], dtype="bool")

        not_mask = ~mask
        y_embed = ops.cumsum(ops.cast(not_mask, "float32"), axis=1)
        x_embed = ops.cumsum(ops.cast(not_mask, "float32"), axis=2)

        if self.normalize:
            eps = 1e-6
            y_embed = (y_embed - 0.5) / (y_embed[:, -1:, :] + eps) * self.scale
            x_embed = (x_embed - 0.5) / (x_embed[:, :, -1:] + eps) * self.scale

        dim_t = ops.arange(self.num_pos_feats, dtype="float32")
        dim_t = self.temperature ** (2 * (dim_t // 2) / self.num_pos_feats)

        pos_x = x_embed[..., None] / dim_t
        pos_y = y_embed[..., None] / dim_t

        pos_x = ops.stack(
            [ops.sin(pos_x[..., 0::2]), ops.cos(pos_x[..., 1::2])], axis=4
        )
        pos_x = ops.reshape(pos_x, (*ops.shape(pos_x)[:3], -1))

        pos_y = ops.stack(
            [ops.sin(pos_y[..., 0::2]), ops.cos(pos_y[..., 1::2])], axis=4
        )
        pos_y = ops.reshape(pos_y, (*ops.shape(pos_y)[:3], -1))

        pos = ops.concatenate([pos_y, pos_x], axis=3)
        # Transpose to (batch, H, W, channels) -> (batch, channels, H, W)
        pos = ops.transpose(pos, [0, 3, 1, 2])
        return pos

    def compute_output_shape(self, input_shape: Tuple[Optional[int], ...]) -> Tuple[Optional[int], ...]:
        """Compute the output shape of the layer.

        :param input_shape: Shape of the input tensor.
        :type input_shape: Tuple[Optional[int], ...]
        :return: Output shape tuple
            ``(batch_size, 2 * num_pos_feats, H, W)``.
        :rtype: Tuple[Optional[int], ...]
        """
        batch_size, h, w = input_shape[0], input_shape[1], input_shape[2]
        return batch_size, 2 * self.num_pos_feats, h, w

    def get_config(self) -> Dict[str, Any]:
        """Return configuration for serialization.

        :return: Dictionary containing all ``__init__`` parameters.
        :rtype: Dict[str, Any]
        """
        config = super().get_config()
        config.update({
            "num_pos_feats": self.num_pos_feats,
            "temperature": self.temperature,
            "normalize": self.normalize,
            "scale": self.scale
        })
        return config

# ---------------------------------------------------------------------
