repos:
-   repo: local
    hooks:
    -   id: python-test
        name: Run Python tests
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
