"""Guards for the H-Net ``arch_layout`` mini-language parser and variant table.

What this file pins
-------------------
1. The parse of EVERY shipped layout string, against a HAND-WRITTEN expected tree.
   "Hand-written" is load-bearing: the expected structures below were transcribed by
   reading ``/media/arxwn/data_fast/repositories/hnet/configs/*.json`` and applying the
   grammar by hand. None of them was produced by calling the parser and pasting its
   output -- a pin generated by the code under test validates nothing.
2. The ``n_residuals`` arithmetic, restated in prose in each test's docstring so that a
   future reader can re-derive it without running anything.
3. The six variant rows, each against the numbers in its own JSON file, so a row
   transcribed from the wrong JSON fails.
4. The validation arms: malformed layout strings, unknown letters, wrong-length lists,
   out-of-range and negative stage indices.

Every "these agree" assertion has a "these differ" twin: an equality that would also hold
if the parser collapsed the distinction it is meant to preserve is not a guard.

The subject is pure Python -- no Keras import, no backend, no device.
"""

import re

import pytest

from dl_techniques.models.language.hnet.config import (
    MODEL_VARIANTS,
    MIXER_ATTENTION,
    MIXER_MAMBA2,
    AttnSpec,
    BlockSpec,
    HNetArchConfig,
    IsotropicSpec,
    SSMSpec,
    StageSpec,
    get_stage_cfg,
    get_variant_config,
    n_residuals,
    n_residuals_by_stage,
    parse_arch_layout,
    stage_count,
)


# ---------------------------------------------------------------------
# A read-only view of a parsed tree, so the hand-written pins stay readable.
# ---------------------------------------------------------------------


def as_tree(node):
    """Flatten a parsed node into nested tuples of plain values.

    Reads only public attributes; it introduces no parsing logic of its own, so the
    expected literals below remain hand-derived rather than machine-generated.
    """
    if isinstance(node, IsotropicSpec):
        return (
            "iso",
            node.layout,
            node.stage_idx,
            node.role,
            tuple((b.kind, b.n_layer) for b in node.blocks),
            node.height,
        )
    assert isinstance(node, StageSpec)
    return (
        "stage",
        node.stage_idx,
        node.is_innermost,
        None if node.encoder is None else as_tree(node.encoder),
        as_tree(node.main),
        None if node.decoder is None else as_tree(node.decoder),
    )


# ---------------------------------------------------------------------
# HAND-WRITTEN expected trees, one per shipped config.
# Derivation of each `height`: lowercase letter contributes n_layer, uppercase
# contributes 2 * n_layer (mixer + SwiGLU MLP each write the residual stream).
# ---------------------------------------------------------------------

# configs/hnet_1stage_L.json  -> ["m4", ["T22"], "m4"]
TREE_1STAGE_L = (
    "stage",
    0,
    False,
    ("iso", "m4", 0, "encoder", (("m", 4),), 4),
    (
        "stage",
        1,
        True,
        None,
        ("iso", "T22", 1, "main", (("T", 22),), 44),
        None,
    ),
    ("iso", "m4", 0, "decoder", (("m", 4),), 4),
)

# configs/hnet_1stage_XL.json -> ["m4", ["T24"], "m4"]
TREE_1STAGE_XL = (
    "stage",
    0,
    False,
    ("iso", "m4", 0, "encoder", (("m", 4),), 4),
    (
        "stage",
        1,
        True,
        None,
        ("iso", "T24", 1, "main", (("T", 24),), 48),
        None,
    ),
    ("iso", "m4", 0, "decoder", (("m", 4),), 4),
)


def _two_stage_tree(inner_layout, inner_n_layer, inner_height):
    """The shared 2-stage skeleton; only the innermost group differs across the four."""
    return (
        "stage",
        0,
        False,
        ("iso", "m4", 0, "encoder", (("m", 4),), 4),
        (
            "stage",
            1,
            False,
            ("iso", "T1m4", 1, "encoder", (("T", 1), ("m", 4)), 6),
            (
                "stage",
                2,
                True,
                None,
                (
                    "iso",
                    inner_layout,
                    2,
                    "main",
                    (("T", inner_n_layer),),
                    inner_height,
                ),
                None,
            ),
            ("iso", "m4T1", 1, "decoder", (("m", 4), ("T", 1)), 6),
        ),
        ("iso", "m4", 0, "decoder", (("m", 4),), 4),
    )


# configs/hnet_2stage_L.json           -> inner "T26", height 2*26 = 52
TREE_2STAGE_L = _two_stage_tree("T26", 26, 52)
# configs/hnet_2stage_XL.json          -> inner "T27", height 2*27 = 54
TREE_2STAGE_XL = _two_stage_tree("T27", 27, 54)
# configs/hnet_2stage_XL_chinese.json  -> inner "T30", height 2*30 = 60
TREE_2STAGE_XL_CHINESE = _two_stage_tree("T30", 30, 60)
# configs/hnet_2stage_XL_code.json     -> inner "T28", height 2*28 = 56
TREE_2STAGE_XL_CODE = _two_stage_tree("T28", 28, 56)

#: variant name -> (layout as it appears in the JSON, hand-written expected tree)
SHIPPED_LAYOUTS = {
    "hnet_1stage_L": (["m4", ["T22"], "m4"], TREE_1STAGE_L),
    "hnet_1stage_XL": (["m4", ["T24"], "m4"], TREE_1STAGE_XL),
    "hnet_2stage_L": (["m4", ["T1m4", ["T26"], "m4T1"], "m4"], TREE_2STAGE_L),
    "hnet_2stage_XL": (["m4", ["T1m4", ["T27"], "m4T1"], "m4"], TREE_2STAGE_XL),
    "hnet_2stage_XL_chinese": (
        ["m4", ["T1m4", ["T30"], "m4T1"], "m4"],
        TREE_2STAGE_XL_CHINESE,
    ),
    "hnet_2stage_XL_code": (
        ["m4", ["T1m4", ["T28"], "m4T1"], "m4"],
        TREE_2STAGE_XL_CODE,
    ),
}


class TestShippedLayoutsParseToTheHandWrittenTree:
    """Every shipped layout string parses to its hand-derived structure."""

    @pytest.mark.parametrize("variant", sorted(SHIPPED_LAYOUTS))
    def test_layout_parses_to_the_hand_written_tree(self, variant):
        layout, expected = SHIPPED_LAYOUTS[variant]
        assert as_tree(parse_arch_layout(layout)) == expected

    @pytest.mark.parametrize("variant", sorted(SHIPPED_LAYOUTS))
    def test_the_variant_row_carries_that_same_layout(self, variant):
        layout, expected = SHIPPED_LAYOUTS[variant]
        assert as_tree(MODEL_VARIANTS[variant].stage_spec) == expected

    def test_the_six_trees_are_not_all_the_same(self):
        """The 'agrees' twin: four distinct trees across the six variants.

        The two XL 2-stage variants differ from each other and from the L one only in the
        innermost group, so a parser that ignored the inner layout string would make all
        four 2-stage trees equal.
        """
        trees = {as_tree(cfg.stage_spec) for cfg in MODEL_VARIANTS.values()}
        assert len(trees) == 6

    def test_a_wrong_inner_count_is_not_accepted_as_equal(self):
        """T26 and T27 must not parse to the same tree."""
        assert as_tree(parse_arch_layout(["m4", ["T26"], "m4"])) != as_tree(
            parse_arch_layout(["m4", ["T27"], "m4"])
        )


class TestLetterSemantics:
    """Letter identity picks the mixer; letter CASE picks whether an MLP is present."""

    @pytest.mark.parametrize(
        "kind,mixer,has_mlp,height",
        [
            ("m", MIXER_MAMBA2, False, 3),
            ("M", MIXER_MAMBA2, True, 6),
            ("t", MIXER_ATTENTION, False, 3),
            ("T", MIXER_ATTENTION, True, 6),
        ],
    )
    def test_block_semantics(self, kind, mixer, has_mlp, height):
        block = BlockSpec(kind=kind, n_layer=3)
        assert block.mixer == mixer
        assert block.has_mlp is has_mlp
        assert block.height == height

    def test_case_changes_the_height_of_the_same_letter(self):
        """The 'differ' twin for case sensitivity: m4 is 4, M4 is 8."""
        lower = parse_arch_layout(["m4"])
        upper = parse_arch_layout(["M4"])
        assert lower.main.height == 4
        assert upper.main.height == 8
        assert lower.main.height != upper.main.height

    def test_case_does_not_change_the_mixer_family(self):
        """The 'agree' twin: case is orthogonal to mixer identity."""
        assert BlockSpec("m", 1).mixer == BlockSpec("M", 1).mixer
        assert BlockSpec("t", 1).mixer == BlockSpec("T", 1).mixer
        assert BlockSpec("m", 1).mixer != BlockSpec("t", 1).mixer

    def test_case_is_preserved_in_the_parsed_kind(self):
        assert parse_arch_layout(["M4"]).main.blocks[0].kind == "M"
        assert parse_arch_layout(["m4"]).main.blocks[0].kind == "m"

    def test_arch_full_expands_groups_in_order(self):
        spec = parse_arch_layout(["m2T1"])
        assert spec.main.arch_full == ("m", "m", "T")
        assert parse_arch_layout(["T1m2"]).main.arch_full == ("T", "m", "m")

    def test_group_order_matters(self):
        """'differ' twin for order: m4T1 and T1m4 have equal height but differ."""
        a = parse_arch_layout(["m4T1"]).main
        b = parse_arch_layout(["T1m4"]).main
        assert a.height == b.height == 6
        assert a.arch_full != b.arch_full


class TestEncoderDecoderSlots:
    """Slot 0 is the encoder and slot 2 is the decoder -- never the other way round."""

    def test_shipped_stage_one_slots_are_not_interchangeable(self):
        """`T1m4` is the stage-1 encoder and `m4T1` the stage-1 decoder."""
        spec = parse_arch_layout(SHIPPED_LAYOUTS["hnet_2stage_XL"][0])
        assert spec.main.encoder.layout == "T1m4"
        assert spec.main.decoder.layout == "m4T1"
        assert spec.main.encoder.layout != spec.main.decoder.layout

    def test_an_asymmetric_layout_keeps_its_slots(self):
        spec = parse_arch_layout(["m1", ["T2"], "t3"])
        assert (spec.encoder.layout, spec.encoder.role) == ("m1", "encoder")
        assert (spec.decoder.layout, spec.decoder.role) == ("t3", "decoder")

    def test_a_symmetric_layout_agrees_on_both_slots(self):
        """'agree' twin: when the two strings are equal the two stacks match."""
        spec = parse_arch_layout(["m4", ["T2"], "m4"])
        assert spec.encoder.blocks == spec.decoder.blocks
        assert spec.encoder.role != spec.decoder.role


class TestNesting:
    """The middle slot recurses; stage indices count from the outside in."""

    @pytest.mark.parametrize(
        "variant,expected_stages",
        [
            ("hnet_1stage_L", 2),
            ("hnet_1stage_XL", 2),
            ("hnet_2stage_L", 3),
            ("hnet_2stage_XL", 3),
            ("hnet_2stage_XL_chinese", 3),
            ("hnet_2stage_XL_code", 3),
        ],
    )
    def test_stage_count(self, variant, expected_stages):
        assert stage_count(MODEL_VARIANTS[variant].stage_spec) == expected_stages
        assert MODEL_VARIANTS[variant].num_stages == expected_stages

    def test_one_stage_and_two_stage_counts_differ(self):
        """'differ' twin: recursion that stopped early would flatten these to equal."""
        assert stage_count(parse_arch_layout(["m4", ["T22"], "m4"])) != stage_count(
            parse_arch_layout(["m4", ["T1m4", ["T27"], "m4T1"], "m4"])
        )

    def test_only_the_innermost_stage_is_marked_innermost(self):
        spec = parse_arch_layout(SHIPPED_LAYOUTS["hnet_2stage_XL"][0])
        assert spec.is_innermost is False
        assert spec.main.is_innermost is False
        assert spec.main.main.is_innermost is True

    def test_the_innermost_stage_has_no_encoder_or_decoder(self):
        inner = parse_arch_layout(SHIPPED_LAYOUTS["hnet_2stage_XL"][0]).main.main
        assert inner.encoder is None
        assert inner.decoder is None
        assert isinstance(inner.main, IsotropicSpec)

    def test_stage_indices_increase_by_one_inward(self):
        spec = parse_arch_layout(SHIPPED_LAYOUTS["hnet_2stage_XL"][0])
        assert spec.stage_idx == 0
        assert spec.encoder.stage_idx == 0
        assert spec.main.stage_idx == 1
        assert spec.main.encoder.stage_idx == 1
        assert spec.main.main.stage_idx == 2
        assert spec.main.main.main.stage_idx == 2

    def test_deep_nesting_beyond_the_shipped_configs(self):
        """D-001: the port carries the full generality, not just 1- and 2-stage."""
        spec = parse_arch_layout(["m1", ["m1", ["m1", ["t1"], "m1"], "m1"], "m1"])
        assert stage_count(spec) == 4
        assert spec.main.main.main.is_innermost is True


class TestNResiduals:
    r"""``n_residuals`` sums ``Isotropic.height`` over the WHOLE nested hierarchy.

    Worked derivation for ``hnet_1stage_L`` (``configs/hnet_1stage_L.json``,
    ``arch_layout = ["m4", ["T22"], "m4"]``), restated per F-01 section 8:

    * encoder ``m4``  -- lowercase, so ``+4``  (mixer only writes the residual stream)
    * decoder ``m4``  -- lowercase, so ``+4``
    * innermost ``T22`` -- UPPERCASE, so ``+2 * 22 = +44`` (mixer AND SwiGLU MLP)

    Total ``4 + 4 + 44 = 52``. This is the denominator of the depth-scaled init
    ``std = 0.02 / sqrt(n_residuals)``, so a wrong value silently mis-scales every
    residual-writing projection in the model.
    """

    def test_hnet_1stage_l_is_52(self):
        assert n_residuals(MODEL_VARIANTS["hnet_1stage_L"].stage_spec) == 52
        assert MODEL_VARIANTS["hnet_1stage_L"].n_residuals == 52

    @pytest.mark.parametrize(
        "variant,expected",
        [
            # 4 (m4 enc) + 4 (m4 dec) + 2*22 = 52
            ("hnet_1stage_L", 52),
            # 4 + 4 + 2*24 = 56
            ("hnet_1stage_XL", 56),
            # 4 + 4 | 6 (T1m4 = 2+4) + 6 (m4T1 = 4+2) | 2*26 = 8 + 12 + 52 = 72
            ("hnet_2stage_L", 72),
            # 8 + 12 + 2*27 = 74
            ("hnet_2stage_XL", 74),
            # 8 + 12 + 2*30 = 80
            ("hnet_2stage_XL_chinese", 80),
            # 8 + 12 + 2*28 = 76
            ("hnet_2stage_XL_code", 76),
        ],
    )
    def test_every_variant(self, variant, expected):
        assert n_residuals(MODEL_VARIANTS[variant].stage_spec) == expected

    def test_uppercase_doubles_and_lowercase_does_not(self):
        """'differ' twin for the +2n rule: the same counts, opposite case."""
        assert n_residuals(parse_arch_layout(["m4", ["t22"], "m4"])) == 30
        assert n_residuals(parse_arch_layout(["m4", ["T22"], "m4"])) == 52
        assert n_residuals(parse_arch_layout(["M4", ["T22"], "M4"])) == 60

    def test_it_spans_the_whole_hierarchy_not_one_stage(self):
        """Dropping any level would make this equal to a strict subset's total."""
        spec = MODEL_VARIANTS["hnet_2stage_XL"].stage_spec
        inner_only = spec.main.main.main.height
        assert inner_only == 54
        assert n_residuals(spec) == 74
        assert n_residuals(spec) != inner_only

    def test_by_stage_is_the_reference_outside_in_cumulative(self):
        """``hnet.py:121-147`` threads ``parent_residuals`` inward, one value per stage.

        ``hnet_1stage_L``: the outer m4/m4 sandwich is scaled against 4 + 4 = 8, and the
        innermost T22 against 8 + 44 = 52.
        """
        assert n_residuals_by_stage(MODEL_VARIANTS["hnet_1stage_L"].stage_spec) == (
            8,
            52,
        )
        assert n_residuals_by_stage(MODEL_VARIANTS["hnet_2stage_XL"].stage_spec) == (
            8,
            20,
            74,
        )

    def test_the_last_cumulative_equals_the_hierarchy_total(self):
        for name, cfg in MODEL_VARIANTS.items():
            spec = cfg.stage_spec
            assert n_residuals_by_stage(spec)[-1] == n_residuals(spec), name

    def test_the_earlier_cumulatives_do_not(self):
        """'differ' twin: only the LAST element coincides with the total."""
        spec = MODEL_VARIANTS["hnet_2stage_XL"].stage_spec
        assert n_residuals_by_stage(spec)[0] != n_residuals(spec)
        assert n_residuals_by_stage(spec)[1] != n_residuals(spec)


class TestGetStageCfg:
    """``get_stage_cfg`` indexes sequences by stage and passes scalars through."""

    def test_attn_cfg_is_indexed_per_stage(self):
        attn = MODEL_VARIANTS["hnet_2stage_XL"].attn_cfg
        assert get_stage_cfg(attn, 0) == {
            "num_heads": 16,
            "rotary_emb_dim": 32,
            "window_size": 1023,
        }
        assert get_stage_cfg(attn, 2) == {
            "num_heads": 16,
            "rotary_emb_dim": 64,
            "window_size": -1,
        }

    def test_two_stages_of_the_same_config_differ(self):
        """'differ' twin: an indexer that ignored stage_idx would return one dict."""
        attn = MODEL_VARIANTS["hnet_2stage_XL"].attn_cfg
        assert get_stage_cfg(attn, 0) != get_stage_cfg(attn, 2)

    def test_stages_with_identical_entries_agree(self):
        """'agree' twin: stages 0 and 1 of hnet_2stage_L share every attn value."""
        attn = MODEL_VARIANTS["hnet_2stage_L"].attn_cfg
        assert get_stage_cfg(attn, 0) == get_stage_cfg(attn, 1)

    def test_scalars_pass_through_unindexed(self):
        ssm = MODEL_VARIANTS["hnet_2stage_XL"].ssm_cfg
        expected = {"d_conv": 4, "expand": 2, "d_state": 128}
        assert get_stage_cfg(ssm, 0) == expected
        assert get_stage_cfg(ssm, 2) == expected

    def test_a_scalar_field_is_not_indexed(self):
        """A scalar that got indexed would raise TypeError, not return the int."""
        assert get_stage_cfg(SSMSpec(d_conv=4, expand=2, d_state=128), 7)["d_conv"] == 4

    def test_stage_index_out_of_range_raises(self):
        attn = MODEL_VARIANTS["hnet_1stage_L"].attn_cfg
        with pytest.raises(IndexError, match="out of range"):
            get_stage_cfg(attn, 2)

    def test_negative_stage_index_raises_instead_of_wrapping(self):
        attn = MODEL_VARIANTS["hnet_1stage_L"].attn_cfg
        with pytest.raises(IndexError, match="non-negative"):
            get_stage_cfg(attn, -1)

    def test_a_non_dataclass_raises(self):
        with pytest.raises(TypeError, match="dataclass"):
            get_stage_cfg({"num_heads": [16]}, 0)


class TestLayoutValidation:
    """Malformed layouts fail loudly instead of parsing to something smaller."""

    @pytest.mark.parametrize(
        "bad",
        ["m", "4", "m4x", "xm4", "m4 T1", "m4,T1", "m-4", "mm4", "m4T"],
    )
    def test_malformed_layout_strings_raise(self, bad):
        with pytest.raises(ValueError, match="malformed|empty"):
            parse_arch_layout([bad])

    @pytest.mark.parametrize("letter", ["a", "q", "s", "n", "x", "Z"])
    def test_unknown_letters_raise(self, letter):
        with pytest.raises(ValueError, match="malformed|empty"):
            parse_arch_layout([f"{letter}4"])

    def test_re_findall_alone_would_have_silently_dropped_the_junk(self):
        """Why the exact-reconstruction check exists, stated as a measurement.

        ``re.findall`` on ``"m4x"`` happily returns ``[("m", "4")]``. Without the
        reconstruction check the parser would build a 4-layer Mamba stack from a string
        the user did not write.
        """
        assert re.findall(r"([mMtT])(\d+)", "m4x") == [("m", "4")]
        with pytest.raises(ValueError):
            parse_arch_layout(["m4x"])

    def test_a_zero_layer_group_raises(self):
        with pytest.raises(ValueError, match="at least one block"):
            parse_arch_layout(["m0"])

    @pytest.mark.parametrize("length", [0, 2, 4, 5])
    def test_wrong_length_layout_lists_raise(self, length):
        with pytest.raises(ValueError, match="length"):
            parse_arch_layout(["m1"] * length)

    def test_lengths_one_and_three_are_accepted(self):
        """'agree' twin for the length check."""
        assert parse_arch_layout(["m1"]).is_innermost is True
        assert parse_arch_layout(["m1", ["t1"], "m1"]).is_innermost is False

    def test_a_bare_string_is_not_a_layout(self):
        with pytest.raises(TypeError, match="must be a list"):
            parse_arch_layout("m4")

    def test_a_non_innermost_middle_slot_must_be_a_list(self):
        with pytest.raises(TypeError, match="must be a list"):
            parse_arch_layout(["m4", "T22", "m4"])

    def test_an_encoder_slot_must_be_a_string(self):
        with pytest.raises(TypeError, match="must be a string"):
            parse_arch_layout([["m4"], ["T22"], "m4"])

    def test_the_innermost_slot_must_be_a_string(self):
        with pytest.raises(TypeError, match="must be a string"):
            parse_arch_layout([["m4"]])


class TestVariantTable:
    """Each row's numbers must come from its own ``configs/*.json``."""

    def test_the_table_holds_exactly_the_six_shipped_variants(self):
        assert sorted(MODEL_VARIANTS) == [
            "hnet_1stage_L",
            "hnet_1stage_XL",
            "hnet_2stage_L",
            "hnet_2stage_XL",
            "hnet_2stage_XL_chinese",
            "hnet_2stage_XL_code",
        ]

    @pytest.mark.parametrize(
        "variant,d_model,d_intermediate,num_heads,rotary,window",
        [
            # configs/hnet_1stage_L.json
            (
                "hnet_1stage_L",
                (1024, 1536),
                (0, 4096),
                (16, 16),
                (32, 48),
                (1023, -1),
            ),
            # configs/hnet_1stage_XL.json
            (
                "hnet_1stage_XL",
                (1024, 2048),
                (0, 5504),
                (16, 16),
                (32, 64),
                (1023, -1),
            ),
            # configs/hnet_2stage_L.json
            (
                "hnet_2stage_L",
                (1024, 1024, 1536),
                (0, 2816, 4096),
                (16, 16, 16),
                (32, 32, 48),
                (1023, 1023, -1),
            ),
            # configs/hnet_2stage_XL.json
            (
                "hnet_2stage_XL",
                (1024, 1536, 2048),
                (0, 4096, 5504),
                (16, 16, 16),
                (32, 48, 64),
                (1023, 1023, -1),
            ),
            # configs/hnet_2stage_XL_chinese.json
            (
                "hnet_2stage_XL_chinese",
                (1024, 1536, 2048),
                (0, 4096, 5504),
                (16, 16, 16),
                (32, 48, 64),
                (1023, 1023, -1),
            ),
            # configs/hnet_2stage_XL_code.json
            (
                "hnet_2stage_XL_code",
                (1024, 1536, 2048),
                (0, 4096, 5504),
                (16, 16, 16),
                (32, 48, 64),
                (1023, 1023, -1),
            ),
        ],
    )
    def test_variant_dimensions(
        self, variant, d_model, d_intermediate, num_heads, rotary, window
    ):
        cfg = MODEL_VARIANTS[variant]
        assert cfg.d_model == d_model
        assert cfg.d_intermediate == d_intermediate
        assert cfg.attn_cfg.num_heads == num_heads
        assert cfg.attn_cfg.rotary_emb_dim == rotary
        assert cfg.attn_cfg.window_size == window

    def test_the_l_and_xl_one_stage_rows_are_not_the_same(self):
        """'differ' twin: a row transcribed from the neighbouring JSON would collide."""
        assert (
            MODEL_VARIANTS["hnet_1stage_L"].d_model
            != MODEL_VARIANTS["hnet_1stage_XL"].d_model
        )
        assert (
            MODEL_VARIANTS["hnet_2stage_L"].d_intermediate
            != MODEL_VARIANTS["hnet_2stage_XL"].d_intermediate
        )

    def test_the_three_xl_two_stage_rows_share_dims_and_differ_only_in_depth(self):
        """'agree' twin: XL, _chinese and _code differ ONLY in the innermost group."""
        names = ["hnet_2stage_XL", "hnet_2stage_XL_chinese", "hnet_2stage_XL_code"]
        dims = {MODEL_VARIANTS[n].d_model for n in names}
        assert len(dims) == 1
        inner = {MODEL_VARIANTS[n].stage_spec.main.main.main.layout for n in names}
        assert inner == {"T27", "T30", "T28"}

    @pytest.mark.parametrize("variant", sorted(SHIPPED_LAYOUTS))
    def test_every_row_shares_the_reference_ssm_values(self, variant):
        assert MODEL_VARIANTS[variant].ssm_cfg == SSMSpec(
            d_conv=4, expand=2, d_state=128
        )

    @pytest.mark.parametrize("variant", sorted(SHIPPED_LAYOUTS))
    def test_every_row_is_byte_vocab_and_untied(self, variant):
        assert MODEL_VARIANTS[variant].vocab_size == 256
        assert MODEL_VARIANTS[variant].tie_embeddings is False

    def test_get_variant_config_returns_the_row(self):
        assert get_variant_config("hnet_2stage_XL") is MODEL_VARIANTS["hnet_2stage_XL"]

    def test_an_unknown_variant_raises_and_names_the_alternatives(self):
        with pytest.raises(ValueError, match="unknown H-Net variant"):
            get_variant_config("hnet_3stage_XXL")


class TestNoDeadConfigField:
    """H17: ``chunk_size`` must not exist -- ``Mamba2Layer`` has no chunked scan."""

    def test_ssm_spec_has_no_chunk_size(self):
        assert not hasattr(SSMSpec(), "chunk_size")
        assert "chunk_size" not in get_stage_cfg(SSMSpec(), 0)

    def test_serialization_carries_no_chunk_size(self):
        for name, cfg in MODEL_VARIANTS.items():
            assert "chunk_size" not in cfg.to_dict()["ssm_cfg"], name

    def test_the_fields_that_do_exist_are_the_three_live_ones(self):
        """'agree' twin: the absence above is a targeted removal, not an empty spec."""
        assert set(get_stage_cfg(SSMSpec(), 0)) == {"d_conv", "expand", "d_state"}


class TestArchConfigValidation:
    """Per-stage list lengths must agree with the layout's stage count."""

    def _kwargs(self, **overrides):
        base = dict(
            arch_layout=["m4", ["T22"], "m4"],
            d_model=[1024, 1536],
            d_intermediate=[0, 4096],
            attn_cfg=AttnSpec(
                num_heads=[16, 16], rotary_emb_dim=[32, 48], window_size=[1023, -1]
            ),
        )
        base.update(overrides)
        return base

    def test_the_baseline_builds(self):
        """'agree' twin for every rejection below."""
        assert HNetArchConfig(**self._kwargs()).num_stages == 2

    @pytest.mark.parametrize(
        "field,value",
        [
            ("d_model", [1024]),
            ("d_model", [1024, 1536, 2048]),
            ("d_intermediate", [0]),
        ],
    )
    def test_a_wrong_length_per_stage_list_raises(self, field, value):
        with pytest.raises(ValueError, match="declares 2 stages"):
            HNetArchConfig(**self._kwargs(**{field: value}))

    def test_a_wrong_length_attn_list_raises(self):
        bad = AttnSpec(num_heads=[16], rotary_emb_dim=[32, 48], window_size=[1023, -1])
        with pytest.raises(ValueError, match="attn_cfg.num_heads"):
            HNetArchConfig(**self._kwargs(attn_cfg=bad))

    def test_a_malformed_layout_is_rejected_at_construction(self):
        with pytest.raises(ValueError, match="malformed"):
            HNetArchConfig(**self._kwargs(arch_layout=["m4", ["T22x"], "m4"]))

    def test_a_non_positive_d_model_raises(self):
        with pytest.raises(ValueError, match="d_model must be positive"):
            HNetArchConfig(**self._kwargs(d_model=[1024, 0]))

    def test_a_non_integer_d_model_raises(self):
        with pytest.raises(TypeError, match="only integers"):
            HNetArchConfig(**self._kwargs(d_model=[1024, 1536.0]))

    def test_lists_are_stored_as_tuples_so_shared_rows_cannot_be_mutated(self):
        cfg = HNetArchConfig(**self._kwargs())
        assert isinstance(cfg.d_model, tuple)
        assert isinstance(cfg.attn_cfg.window_size, tuple)
        with pytest.raises(TypeError):
            cfg.d_model[0] = 1


class TestPlainDictRoundTrip:
    """``to_dict``/``from_dict`` round-trip by value, JSON-shaped."""

    @pytest.mark.parametrize("variant", sorted(SHIPPED_LAYOUTS))
    def test_round_trip_is_identity(self, variant):
        cfg = MODEL_VARIANTS[variant]
        assert HNetArchConfig.from_dict(cfg.to_dict()) == cfg

    def test_to_dict_is_json_shaped(self):
        import json

        payload = MODEL_VARIANTS["hnet_2stage_XL"].to_dict()
        assert json.loads(json.dumps(payload)) == payload
        assert payload["arch_layout"] == ["m4", ["T1m4", ["T27"], "m4T1"], "m4"]

    def test_two_different_variants_do_not_round_trip_to_each_other(self):
        """'differ' twin: a round-trip that dropped a field would collapse these."""
        a = HNetArchConfig.from_dict(MODEL_VARIANTS["hnet_2stage_XL"].to_dict())
        b = HNetArchConfig.from_dict(MODEL_VARIANTS["hnet_2stage_XL_code"].to_dict())
        assert a != b

    def test_an_unknown_key_is_rejected_not_ignored(self):
        payload = MODEL_VARIANTS["hnet_1stage_L"].to_dict()
        payload["chunk_size"] = 256
        with pytest.raises(KeyError, match="unknown HNetArchConfig keys"):
            HNetArchConfig.from_dict(payload)

    def test_a_missing_required_key_raises(self):
        payload = MODEL_VARIANTS["hnet_1stage_L"].to_dict()
        del payload["d_model"]
        with pytest.raises(KeyError, match="missing required"):
            HNetArchConfig.from_dict(payload)


class TestNoKerasImport:
    """The mini-language stays backend-free so it can be parsed without a device."""

    def test_the_module_source_imports_no_keras(self):
        import inspect

        from dl_techniques.models.language.hnet import config as subject

        source = inspect.getsource(subject)
        code = "\n".join(
            line for line in source.splitlines() if line.lstrip().startswith("import ")
            or line.lstrip().startswith("from ")
        )
        assert "keras" not in code
        assert "tensorflow" not in code
