"""Common utilities shared across training scripts."""

from train.common.gpu import setup_gpu, log_gpu_peak_memory, setup_mixed_precision
from train.common.args import (
    create_base_argument_parser,
    create_ts_argument_parser,
    explicitly_set_flags,
)
from train.common.datasets import load_dataset, load_imagenet_dataset, get_class_names, CIFAR10_MEAN, CIFAR10_STD, IMAGENET_MEAN, IMAGENET_STD, make_imagenet_filesystem_dataset, collect_image_paths, DEFAULT_IMAGE_EXTENSIONS, build_raw_image_dataset, ElementMapFn, IMAGENETTE_TFDS_NAME, IMAGENETTE_NUM_CLASSES, DATASET_NUM_CLASSES, SUPPORTED_DATASETS
from train.common.callbacks import create_callbacks, create_learning_rate_schedule, EpochMetricsPlotCallback
from train.common.augment import augment_patch, augment_pair
from train.common.evaluation import (
    validate_model_loading,
    convert_keras_history_to_training_history,
    create_classification_results,
    generate_training_curves,
    generate_comprehensive_visualizations,
    run_model_analysis,
    setup_visualization_manager,
)
from train.common.nlp import (
    create_tokenizer as create_nlp_tokenizer,
    decode_text,
    load_text_dataset,
    preprocess_mlm_dataset,
    preprocess_classification_dataset,
    create_warmup_lr_schedule,
    create_nlp_callbacks,
    estimate_clm_steps_per_epoch,
    GenerationProbeCallback,
)
from train.common.image_text import (
    IMAGE_MEAN,
    IMAGE_STD,
    read_decode_resize_uint8,
    augment_and_normalize,
    tokenize_captions,
    build_synthetic_image_text_dataset,
    load_coco2017_local_split,
    load_cc3m_local_split,
    make_image_text_tf_dataset,
)
from train.common.megadepth import (
    discover_megadepth_pairs,
    load_and_process_pair as load_megadepth_pair,
    MegaDepthDataset,
)
from train.common.seed import set_seeds
from train.common.config_io import save_config_json, json_numpy_default
from train.common.run_io import (
    TIMESTAMP_FORMAT,
    run_timestamp,
    default_experiment_name,
    prepare_run_dir,
    save_training_history_json,
)
from train.common.stats import (
    mean_std,
    bootstrap_ci,
    paired_permutation_test,
    format_mean_std,
)
from train.common.timeseries import (
    BaseTimeSeriesTrainingConfig,
    WindowedTimeSeriesProcessor,
    TimeSeriesPerformanceCallback,
    BaseTimeSeriesTrainer,
    _prepare_viz_data_from_processor,
    _fill_nans,
)
from train.common.step_plots import plot_step_metrics, StepPlotCallback
from train.common.step_checkpoint import StepCheckpointCallback
from train.common.tfrecord import (
    SchemaSpec,
    IMAGE_TEXT_SCHEMA,
    IMAGE_LABEL_SCHEMA,
    bytes_feature,
    int64_feature,
    int64_list_feature,
    float_feature,
    float_list_feature,
    make_example,
    build_image_text_example,
    build_image_label_example,
    write_tfrecord_shards,
    list_tfrecord_shards,
    read_tfrecord_dataset,
    make_image_text_tf_dataset_from_tfrecord,
)
from train.common.token_superposition import (
    TSTConfig,
    TSTState,
    TSTEmbedding,
    TSTCausalLMLoss,
    TSTPhaseCallback,
    tst_phase1_transform,
    tst_phase2_transform,
    apply_tst,
)


# Explicit re-export surface. This package is a HUB: every name above is
# imported solely to be re-exported, so `__all__` is what marks them as used
# (pyflakes has no `noqa`), and it is the same idiom `train/beit/common.py` and
# `train/graph_energy_transformer/common.py` already use for their re-exports.
# A name added to an import above but NOT added here now shows up as a pyflakes
# 'imported but unused' warning -- that is the intended enforcement, not noise.
__all__ = [
    "apply_tst",
    "augment_and_normalize",
    "augment_pair",
    "augment_patch",
    "BaseTimeSeriesTrainer",
    "BaseTimeSeriesTrainingConfig",
    "bootstrap_ci",
    "build_image_label_example",
    "build_image_text_example",
    "build_raw_image_dataset",
    "build_synthetic_image_text_dataset",
    "bytes_feature",
    "CIFAR10_MEAN",
    "CIFAR10_STD",
    "collect_image_paths",
    "convert_keras_history_to_training_history",
    "create_base_argument_parser",
    "create_callbacks",
    "create_classification_results",
    "create_learning_rate_schedule",
    "create_nlp_callbacks",
    "create_nlp_tokenizer",
    "create_ts_argument_parser",
    "create_warmup_lr_schedule",
    "DATASET_NUM_CLASSES",
    "decode_text",
    "default_experiment_name",
    "DEFAULT_IMAGE_EXTENSIONS",
    "discover_megadepth_pairs",
    "ElementMapFn",
    "EpochMetricsPlotCallback",
    "estimate_clm_steps_per_epoch",
    "explicitly_set_flags",
    "_fill_nans",
    "float_feature",
    "float_list_feature",
    "format_mean_std",
    "generate_comprehensive_visualizations",
    "generate_training_curves",
    "GenerationProbeCallback",
    "get_class_names",
    "IMAGE_LABEL_SCHEMA",
    "IMAGE_MEAN",
    "IMAGE_STD",
    "IMAGE_TEXT_SCHEMA",
    "IMAGENET_MEAN",
    "IMAGENET_STD",
    "IMAGENETTE_NUM_CLASSES",
    "IMAGENETTE_TFDS_NAME",
    "int64_feature",
    "int64_list_feature",
    "json_numpy_default",
    "list_tfrecord_shards",
    "load_cc3m_local_split",
    "load_coco2017_local_split",
    "load_dataset",
    "load_imagenet_dataset",
    "load_megadepth_pair",
    "load_text_dataset",
    "log_gpu_peak_memory",
    "make_example",
    "make_image_text_tf_dataset",
    "make_image_text_tf_dataset_from_tfrecord",
    "make_imagenet_filesystem_dataset",
    "mean_std",
    "MegaDepthDataset",
    "paired_permutation_test",
    "plot_step_metrics",
    "prepare_run_dir",
    "_prepare_viz_data_from_processor",
    "preprocess_classification_dataset",
    "preprocess_mlm_dataset",
    "read_decode_resize_uint8",
    "read_tfrecord_dataset",
    "run_model_analysis",
    "run_timestamp",
    "save_config_json",
    "save_training_history_json",
    "SchemaSpec",
    "set_seeds",
    "setup_gpu",
    "setup_mixed_precision",
    "setup_visualization_manager",
    "StepCheckpointCallback",
    "StepPlotCallback",
    "SUPPORTED_DATASETS",
    "TimeSeriesPerformanceCallback",
    "TIMESTAMP_FORMAT",
    "tokenize_captions",
    "tst_phase1_transform",
    "tst_phase2_transform",
    "TSTCausalLMLoss",
    "TSTConfig",
    "TSTEmbedding",
    "TSTPhaseCallback",
    "TSTState",
    "validate_model_loading",
    "WindowedTimeSeriesProcessor",
    "write_tfrecord_shards",
]
