"""Frozen independent reference: the OFFICIAL ``cvg/LightGlue`` torch model's outputs.

``data/torch_reference.npz`` was generated by running the official ``lightglue.py`` (see
``data/generate_torch_reference.py`` for the commit, torch version and recipe) on CPU. It
holds the torch state dict, the inputs and the official outputs, so this suite checks the
Keras model against an implementation nobody on this project wrote, WITHOUT torch. Weights
load through the test-only transpose mapping in ``weight_loading.py``.

Config: 3 layers, descriptor dim 32, 4 heads, input dim 16 (so ``input_proj`` is live), 24
and 20 keypoints, different image width and height per image.

Tolerances are derived, not fitted. Static float64 run: about 20 rounded stages per layer
(self block, cross block, assignment), three layers chained, each stage a few eps64 of
relative error, so the bound is ``4 * 20 * 3 * eps64 * (1 + max|value|)``. The float32
adaptive runs use the same formula with eps32 for the continuous scores; the discrete
outputs (matches, stop layer, prune counters) must be IDENTICAL.
"""

from pathlib import Path

import numpy as np
import pytest

from dl_techniques.models.vision.keypoints.lightglue.model import LightGlue

from .weight_loading import load_torch_weights

# TF32 matmul would turn the float32 adaptive comparison into a ~1e-3 one.
pytestmark = pytest.mark.usefixtures("tf32_disabled")

REFERENCE = Path(__file__).parent / "data" / "torch_reference.npz"
_EPS64 = float(np.finfo(np.float64).eps)
_EPS32 = float(np.finfo(np.float32).eps)
LAYERS = 3
_STAGES = 20


def _tol(expected, eps):
    return 4 * _STAGES * LAYERS * eps * (1.0 + float(np.abs(expected).max()))


@pytest.fixture(scope="module")
def ref():
    z = np.load(REFERENCE)
    return {k: z[k] for k in z.files}


def _inputs(ref, dtype):
    keys = {"keypoints0": "k0", "keypoints1": "k1", "descriptors0": "d0",
            "descriptors1": "d1", "image_size0": "s0", "image_size1": "s1"}
    return {name: ref[key].astype(dtype) for name, key in keys.items()}


def _build(ref, dtype, **kwargs):
    layers, dim, heads, in_dim = (int(v) for v in ref["config"])
    assert layers == LAYERS
    model = LightGlue(input_dim=in_dim, descriptor_dim=dim, num_layers=layers,
                      num_heads=heads, dtype=dtype, **kwargs)
    model(_inputs(ref, dtype))
    weights = {k[3:]: v for k, v in ref.items() if k.startswith("w__")}
    load_torch_weights(model, weights)
    # Every torch parameter must have been consumed: equal parameter counts.
    n_keras = sum(int(np.prod(v.shape)) for v in model.weights)
    n_torch = sum(int(np.prod(v.shape)) for k, v in weights.items() if k != "confidence_thresholds")
    assert n_keras == n_torch
    return model


@pytest.fixture(scope="module")
def static_out(ref):
    model = _build(ref, "float64")
    return model, {k: np.asarray(v) for k, v in model(_inputs(ref, "float64")).items()}


def test_static_log_assignments_match_the_official_model_per_layer(ref, static_out):
    _, out = static_out
    expected = ref["la"]
    assert out["log_assignments"].shape == (1,) + expected.shape
    assert np.abs(out["log_assignments"][0] - expected).max() < _tol(expected, _EPS64)


def test_static_token_confidences_match(ref, static_out):
    _, out = static_out
    for key, name in (("c0", "token_confidences0"), ("c1", "token_confidences1")):
        assert np.abs(out[name][0] - ref[key]).max() < _tol(ref[key], _EPS64)


def test_static_matches_are_identical_and_scores_match(ref, static_out):
    _, out = static_out
    assert (ref["m0"] > -1).sum() >= 3  # the reference is not a vacuous all-dustbin case
    assert np.array_equal(out["matches0"][0], ref["m0"])
    assert np.array_equal(out["matches1"][0], ref["m1"])
    assert np.abs(out["matching_scores0"][0] - ref["ms0"]).max() < _tol(ref["ms0"], _EPS64)


def _adaptive_tags(ref):
    return sorted({k.split("__")[0] for k in ref if k.startswith("adapt_")})


@pytest.mark.parametrize("tag", ["adapt_stop", "adapt_prune", "adapt_both"])
def test_match_stop_layer_pruning_and_matches_equal_the_official_ones(ref, tag):
    assert tag in _adaptive_tags(ref)
    model = _build(ref, "float32", depth_confidence=float(ref[tag + "__depth"]),
                   width_confidence=float(ref[tag + "__width"]))
    # The same bias shifts the generator applied to the official model.
    for i in range(LAYERS - 1):
        bias = model.confidences[i].token_0.bias
        bias.assign(bias.numpy() + float(ref[tag + "__bias"]))
    bias = model.assignments[0].matchability.bias
    bias.assign(bias.numpy() + float(ref[tag + "__mbias"]))
    result = model.match(_inputs(ref, "float32"))
    assert result["stop"] == int(ref[tag + "__stop"])
    assert np.array_equal(result["prune0"][0], ref[tag + "__p0"])
    assert np.array_equal(result["prune1"][0], ref[tag + "__p1"])
    assert np.array_equal(result["matches0"][0], ref[tag + "__m0"])
    assert np.array_equal(result["matches1"][0], ref[tag + "__m1"])
    scores = ref[tag + "__s0"]
    assert np.abs(result["matching_scores0"][0] - scores).max() < _tol(scores, _EPS32)


def test_the_adaptive_references_exercise_stop_and_pruning(ref):
    """Guard the fixture itself: an early stop and a pruned run must be present."""
    assert int(ref["adapt_stop__stop"]) < LAYERS
    for tag in ("adapt_prune", "adapt_both"):
        assert ref[tag + "__p0"].min() < LAYERS and ref[tag + "__p1"].min() < LAYERS


def test_the_tolerance_is_tight_enough_to_see_a_convention_change(ref, static_out):
    """Sensitivity control (RED in place): a LayerNorm epsilon of 1e-3 instead of 1e-5."""
    model = _build(ref, "float64")
    swapped = 0
    for block in list(model.self_blocks) + list(model.cross_blocks):
        block.ffn_1.epsilon = 1e-3
        swapped += 1
    assert swapped == 2 * LAYERS
    out = np.asarray(model(_inputs(ref, "float64"))["log_assignments"])[0]
    assert np.abs(out - ref["la"]).max() > 1000 * _tol(ref["la"], _EPS64)
