"""Train ColBERT **v2** with the cross-encoder KL distillation objective.

The v2 recipe (Santhanam et al., 2021): score an ``nway`` candidate tuple with
MaxSim, take ``log_softmax`` of the student scores and ``log_softmax`` of the
``distillation_alpha``-scaled teacher scores, and minimize the batch-mean KL
divergence between the two log-probability rows. Its partner loss is
:class:`~dl_techniques.losses.ColBERTDistillationLoss`; the v1 recipe and its
partner :class:`~dl_techniques.losses.ColBERTPairwiseSoftmaxLoss` live in
``train_colbert_v1.py``.

**v2 builds the same network as v1.** ``create_colbert_v2`` and
``create_colbert_v1`` differ in documentation and intent, not in architecture --
the official ``stanford-futuredata/ColBERT`` repository ships one
``colbert/modeling/colbert.py`` for both papers. What v2 changed is the
supervision (this file) and the index (the index-time
:class:`~dl_techniques.models.language.colbert.ResidualCompressionCodec`, which
never appears in the forward pass or in any loss and is therefore not used here).

.. warning::

   **Any checkpoint this script produces is a WIRING result, never a
   retrieval-quality claim.** Three independent reasons here, one more than v1:

   1. **There are no pretrained weights.** Not for ColBERT, and not for the BERT
      backbone either -- ``ColBERT.from_variant(pretrained=True)`` and
      ``BERT.from_variant(pretrained=True)`` both raise ``NotImplementedError``
      in this repository. Training starts from random initialization, where
      published ColBERTv2 starts from a pretrained backbone.
   2. **The data is synthetic**, generated by ``common.py``. There is no MS
      MARCO and no other IR dataset in this repository.
   3. **There is no cross-encoder teacher.** Published ColBERTv2 distills from a
      trained cross-encoder re-ranker. No such model exists here, so the
      "teacher" scores are generated alongside the data by the same seeded
      process that decided which document is the positive -- a label wearing a
      teacher's clothes. It exercises the distillation loss's real code path
      (grouping, alpha scaling, the two log-softmaxes, the KL) and it teaches
      the student nothing a cross-encoder knows.

   Do not report a loss from this script as a retrieval number, and do not
   compare it to a published one.

Usage::

    MPLBACKEND=Agg CUDA_VISIBLE_DEVICES=1 .venv/bin/python \\
        -m train.language.colbert.train_colbert_v2 --variant tiny --nway 4

    # tiny end-to-end wiring check, seconds on CPU:
    MPLBACKEND=Agg CUDA_VISIBLE_DEVICES="" .venv/bin/python \\
        -m train.language.colbert.train_colbert_v2 --smoke
"""

import argparse
from typing import Optional, Sequence, Tuple

import keras

from train.common import setup_gpu, set_seeds
from train.common.args import config_values_from_args
from train.common.callbacks import best_checkpoint_path, create_callbacks
from train.common.optimizer import build_optimizer

from dl_techniques.losses import ColBERTDistillationLoss
from dl_techniques.models.language.colbert import ColBERT, create_colbert_v2
from dl_techniques.utils.logger import logger

from train.language.colbert.common import (
    CLI_TO_CONFIG,
    SMOKE_PRESET,
    TrainingConfig,
    add_common_arguments,
    build_datasets,
    build_model,
    steps_per_epoch_for,
)

__all__ = [
    "V2_CLI_TO_CONFIG",
    "V2_DEFAULT_NWAY",
    "build_parser",
    "main",
    "train_colbert_v2",
]

#: v2 trains on a listwise tuple, not a triple. The reference uses 64; 4 is the
#: default here because the synthetic generator draws every negative from a
#: DISTINCT topic and only carries a handful of them. Raise it with ``--nway``
#: once a real corpus supplies the candidates.
V2_DEFAULT_NWAY: int = 4

#: v1's wiring table plus the v2-only ``--distillation-alpha``. Built by
#: extension rather than retyped, so a field added to the shared table reaches
#: both trainers automatically.
V2_CLI_TO_CONFIG = {
    **CLI_TO_CONFIG,
    "distillation_alpha": "distillation_alpha",
}


# ---------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    """Build the v2 parser.

    Interface contract (2 callers: :func:`main` and the trainer tests, which
    resolve a full argv through this exact parser -- the test must not build a
    parser of its own, or it measures a different option table than the one that
    ships):

    :returns: A parser carrying every flag in :data:`V2_CLI_TO_CONFIG` plus
        ``--gpu``, with ``--nway`` defaulted to :data:`V2_DEFAULT_NWAY`.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Train ColBERT v2 (cross-encoder KL distillation) on synthetic "
            "nway tuples with synthetic teacher scores. Wiring only -- no "
            "pretrained weights, no IR dataset, no real teacher."
        )
    )
    add_common_arguments(parser)
    parser.add_argument(
        "--distillation-alpha", type=float,
        default=TrainingConfig.distillation_alpha,
        help="Scales the teacher scores before their log-softmax. Must be > 0.",
    )
    # The listwise recipe's own group size, overriding the shared default of 2.
    parser.set_defaults(nway=V2_DEFAULT_NWAY)
    return parser


# ---------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------


def train_colbert_v2(
    config: TrainingConfig,
) -> Tuple[ColBERT, keras.callbacks.History, str]:
    """Run the v2 recipe end to end.

    :param config: Fully resolved configuration. ``distillation_alpha`` is read
        here and nowhere in v1.
    :type config: TrainingConfig
    :returns: ``(model, history, results_dir)``. ``results_dir`` is the
        timestamped run directory the callbacks wrote into -- the single source
        of truth for artifact paths.
    :rtype: Tuple[ColBERT, keras.callbacks.History, str]
    """
    logger.info("=" * 70)
    logger.info("ColBERT v2 -- KL distillation on SYNTHETIC data")
    logger.info(
        "WIRING RESULT ONLY: no pretrained weights, no IR corpus, no real "
        "cross-encoder teacher."
    )
    logger.info("=" * 70)
    logger.info(f"Config: {config!r}")

    set_seeds(config.seed)

    # Unlike v1, the label side carries real numbers: the synthetic teacher
    # scores the distillation loss takes its target distribution from.
    train_dataset, val_dataset, _ = build_datasets(config, use_teacher_targets=True)

    steps_per_epoch = steps_per_epoch_for(config)
    optimizer = build_optimizer(config, steps_per_epoch)
    model = build_model(
        config,
        loss=ColBERTDistillationLoss(
            nway=config.nway,
            distillation_alpha=config.distillation_alpha,
        ),
        optimizer=optimizer,
        factory=create_colbert_v2,
    )

    callbacks, results_dir = create_callbacks(
        model_name=f"colbert_v2_{config.colbert_variant}",
        results_dir_prefix=config.results_dir_prefix,
        output_root=config.output_root,
        monitor="val_loss",
        monitor_mode="min",
        patience=config.patience,
        use_lr_schedule=True,
        include_terminate_on_nan=True,
        # The epoch analyzer inspects a single-tensor-output classifier; this
        # model returns a three-key dict and has no class labels.
        include_analyzer=False,
    )
    logger.info(f"Run directory: {results_dir}")

    history = model.fit(
        train_dataset,
        epochs=config.epochs,
        validation_data=val_dataset,
        callbacks=callbacks,
        verbose=2,
    )

    logger.info(f"Best checkpoint: {best_checkpoint_path(results_dir)}")
    logger.info(
        "Reminder: this KL is measured against a synthetic teacher on synthetic "
        "data. It is a wiring signal, not a retrieval metric."
    )
    return model, history, results_dir


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------


def main(argv: Optional[Sequence[str]] = None) -> None:
    """Parse ``argv``, build the config and train.

    :param argv: Tokens without the program name. ``None`` reads ``sys.argv``.
    :type argv: Optional[Sequence[str]]
    """
    parser = build_parser()

    # Every mapped field is forwarded in a LOOP inside `config_values_from_args`.
    # Do NOT replace this with a hand-written `config.x = args.x` list: that is
    # the documented silent-no-op defect, where forgetting one line leaves a
    # flag advertised by --help and consumed by nothing.
    args, values = config_values_from_args(
        parser, argv, V2_CLI_TO_CONFIG, SMOKE_PRESET
    )
    config = TrainingConfig(**values)

    setup_gpu(gpu_id=args.gpu)
    train_colbert_v2(config)


if __name__ == "__main__":
    main()
