"""Train ColBERT **v1** with the pairwise/listwise softmax objective.

The v1 recipe (Khattab & Zaharia, 2020): score a ``<query, positive,
negatives...>`` tuple with MaxSim, reshape the flat score vector into
``(batch, nway)`` rows with the positive at column 0, and take softmax
cross-entropy against a label of zeros. Its partner loss is
:class:`~dl_techniques.losses.ColBERTPairwiseSoftmaxLoss`; the v2 recipe and its
partner :class:`~dl_techniques.losses.ColBERTDistillationLoss` live in
``train_colbert_v2.py``.

.. warning::

   **Any checkpoint this script produces is a WIRING result, never a
   retrieval-quality claim.** Two independent reasons, both structural:

   1. **There are no pretrained weights.** Not for ColBERT, and not for the BERT
      backbone either -- ``ColBERT.from_variant(pretrained=True)`` and
      ``BERT.from_variant(pretrained=True)`` both raise ``NotImplementedError``
      in this repository. Training starts from random initialization, where
      published ColBERT starts from a pretrained ``bert-base``.
   2. **The data is synthetic**, generated by ``common.py``. There is no MS
      MARCO and no other IR dataset in this repository. The synthetic task is
      learnable in principle -- positives repeat the query's words, negatives
      come from a disjoint topic -- but it is solvable by pure term matching and
      it is evaluated on data from the same generator.

   Do not report a loss or an accuracy from this script as a retrieval number,
   and do not compare it to a published one. What a clean run demonstrates is
   that the tokenizer, the model, the loss, the optimizer and the checkpointing
   are connected correctly.

Usage::

    MPLBACKEND=Agg CUDA_VISIBLE_DEVICES=1 .venv/bin/python \\
        -m train.language.colbert.train_colbert_v1 --variant tiny --epochs 3

    # tiny end-to-end wiring check, seconds on CPU:
    MPLBACKEND=Agg CUDA_VISIBLE_DEVICES="" .venv/bin/python \\
        -m train.language.colbert.train_colbert_v1 --smoke
"""

import argparse
from typing import Optional, Sequence, Tuple

import keras

from train.common import setup_gpu, set_seeds
from train.common.args import config_values_from_args
from train.common.callbacks import best_checkpoint_path, create_callbacks
from train.common.optimizer import build_optimizer

from dl_techniques.losses import ColBERTPairwiseSoftmaxLoss
from dl_techniques.models.language.colbert import ColBERT, create_colbert_v1
from dl_techniques.utils.logger import logger

from train.language.colbert.common import (
    CLI_TO_CONFIG,
    SMOKE_PRESET,
    TrainingConfig,
    add_common_arguments,
    build_datasets,
    build_model,
    steps_per_epoch_for,
)

__all__ = ["build_parser", "main", "train_colbert_v1"]


# ---------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    """Build the v1 parser.

    Interface contract (2 callers: :func:`main` and the trainer tests, which
    resolve a full argv through this exact parser -- the test must not build a
    parser of its own, or it measures a different option table than the one that
    ships):

    :returns: A parser carrying every flag in
        :data:`~train.language.colbert.common.CLI_TO_CONFIG` plus ``--gpu``.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Train ColBERT v1 (pairwise softmax cross-entropy) on synthetic "
            "triples. Wiring only -- no pretrained weights, no IR dataset."
        )
    )
    return add_common_arguments(parser)


# ---------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------


def train_colbert_v1(
    config: TrainingConfig,
) -> Tuple[ColBERT, keras.callbacks.History, str]:
    """Run the v1 recipe end to end.

    :param config: Fully resolved configuration.
    :type config: TrainingConfig
    :returns: ``(model, history, results_dir)``. ``results_dir`` is the
        timestamped run directory the callbacks wrote into -- the single source
        of truth for artifact paths.
    :rtype: Tuple[ColBERT, keras.callbacks.History, str]
    """
    logger.info("=" * 70)
    logger.info("ColBERT v1 -- pairwise softmax CE on SYNTHETIC data")
    logger.info("WIRING RESULT ONLY: no pretrained weights, no IR corpus.")
    logger.info("=" * 70)
    logger.info(f"Config: {config!r}")

    set_seeds(config.seed)

    # v1 ignores its label argument entirely (the positive is index 0 by
    # position), so the label side is zeros -- see the loss's own warning.
    train_dataset, val_dataset, _ = build_datasets(config, use_teacher_targets=False)

    steps_per_epoch = steps_per_epoch_for(config)
    optimizer = build_optimizer(config, steps_per_epoch)
    model = build_model(
        config,
        loss=ColBERTPairwiseSoftmaxLoss(nway=config.nway),
        optimizer=optimizer,
        factory=create_colbert_v1,
    )

    callbacks, results_dir = create_callbacks(
        model_name=f"colbert_v1_{config.colbert_variant}",
        results_dir_prefix=config.results_dir_prefix,
        output_root=config.output_root,
        monitor="val_loss",
        monitor_mode="min",
        patience=config.patience,
        use_lr_schedule=True,
        include_terminate_on_nan=True,
        # The epoch analyzer inspects a single-tensor-output classifier; this
        # model returns a three-key dict and has no class labels.
        include_analyzer=False,
    )
    logger.info(f"Run directory: {results_dir}")

    history = model.fit(
        train_dataset,
        epochs=config.epochs,
        validation_data=val_dataset,
        callbacks=callbacks,
        verbose=2,
    )

    logger.info(f"Best checkpoint: {best_checkpoint_path(results_dir)}")
    logger.info(
        "Reminder: this loss is a wiring signal on synthetic data, not a "
        "retrieval metric."
    )
    return model, history, results_dir


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------


def main(argv: Optional[Sequence[str]] = None) -> None:
    """Parse ``argv``, build the config and train.

    :param argv: Tokens without the program name. ``None`` reads ``sys.argv``.
    :type argv: Optional[Sequence[str]]
    """
    parser = build_parser()

    # Every mapped field is forwarded in a LOOP inside `config_values_from_args`.
    # Do NOT replace this with a hand-written `config.x = args.x` list: that is
    # the documented silent-no-op defect, where forgetting one line leaves a
    # flag advertised by --help and consumed by nothing.
    args, values = config_values_from_args(
        parser, argv, CLI_TO_CONFIG, SMOKE_PRESET
    )
    config = TrainingConfig(**values)

    setup_gpu(gpu_id=args.gpu)
    train_colbert_v1(config)


if __name__ == "__main__":
    main()
