import keras
from keras import ops, layers

# ---------------------------------------------------------------------
# local imports
# ---------------------------------------------------------------------

from .nbeats_blocks import NBeatsBlock
from .temporal_convolutional_network import TemporalConvNet

# ---------------------------------------------------------------------

@keras.saving.register_keras_serializable()
class ExogenousBlock(NBeatsBlock):
    """
    N-BEATSx exogenous block incorporating external covariates.

    This block extends the standard N-BEATS architecture by incorporating
    exogenous variables (covariates) to generate backcast and forecast signals.
    Unlike standard N-BEATS blocks where the basis is fixed (Trend/Seasonality)
    or static (Generic), here the basis is dynamic and generated by a TCN
    encoder running on the exogenous variables X.

    The projection follows Eq (9) in Olivares et al. (2021):
        backcast = einsum('btc,bc->bt', basis_backcast, theta_backcast)
        forecast = einsum('btc,bc->bt', basis_forecast, theta_forecast)

    When use_tcn is True (NBEATSx-G), the basis is C = TCN(X). When False
    (NBEATSx-I), the basis is the raw exogenous input X itself.

    **Architecture Overview:**

    .. code-block:: text

        Residual Target y                  Exogenous (x_back, x_fore)
        (batch, B_len * in_dim)            (batch, B_len, exog_dim)
                |                          (batch, F_len, exog_dim)
                v                                    |
        +------------------+                         v
        |  Dense Stack     |               Concatenate along time
        |  (4 Dense layers)|               (batch, B_len+F_len, exog_dim)
        +--------+---------+                         |
                 |                                   v
                 |                          +------------------+
                 |                          | TCN Encoder      |
                 |                          | (or identity     |
                 |                          |  if use_tcn=False)|
                 |                          +--------+---------+
                 |                                   |
                 |                            Split into basis_b, basis_f
                 |                                   |
        +--------+---------+               +---------+---------+
        |                  |               |                   |
        v                  v               v                   v
    Theta_backcast   Theta_forecast    Basis_backcast    Basis_forecast
    (batch, C)       (batch, C)        (batch, B, C)     (batch, F, C)
        |                  |               |                   |
        +--------+---------+               +--------+----------+
                 |                                  |
                 v                                  v
        einsum('btc,bc->bt', basis_b, theta_b)
        einsum('btc,bc->bt', basis_f, theta_f)
                 |                                  |
                 v                                  v
           Backcast                           Forecast
           (batch, B_len)                     (batch, F_len)

    :param exogenous_dim: Number of exogenous features.
    :type exogenous_dim: int
    :param tcn_filters: Number of filters in the TCN encoder.
        Usually equals thetas_dim.
    :type tcn_filters: int
    :param tcn_kernel_size: Kernel size for TCN convolutions.
    :type tcn_kernel_size: int
    :param tcn_dropout: Dropout rate for TCN.
    :type tcn_dropout: float
    :param use_tcn: If True, uses TCN basis (NBEATSx-G). If False, uses
        linear projection of X (NBEATSx-I).
    :type use_tcn: bool
    :param kwargs: Arguments passed to NBeatsBlock.
    """

    def __init__(
            self,
            exogenous_dim: int,
            tcn_filters: int = 16,
            tcn_kernel_size: int = 2,
            tcn_dropout: float = 0.0,
            use_tcn: bool = True,
            **kwargs
    ):
        # In NBEATSx, theta dimension corresponds to the channels of the basis/exog
        # Ensure kwargs['thetas_dim'] matches or is set correctly if not provided
        super().__init__(**kwargs)

        self.exogenous_dim = exogenous_dim
        self.use_tcn = use_tcn
        self.tcn_filters = tcn_filters
        self.tcn_kernel_size = tcn_kernel_size
        self.tcn_dropout = tcn_dropout

        # The encoder for exogenous variables
        if self.use_tcn:
            self.encoder = TemporalConvNet(
                filters=tcn_filters,
                kernel_size=tcn_kernel_size,
                dropout_rate=tcn_dropout
            )
        else:
            # For Interpretable (NBEATSx-I), the basis is just X itself.
            # No complex encoder needed, but we might need projection if dims don't match
            self.encoder = None

        # Redefine Theta layers to match TCN/Exog dimensionality
        # Theta must project to the dimension of the Basis channels
        basis_channels = tcn_filters if use_tcn else exogenous_dim

        self.theta_backcast = layers.Dense(
            basis_channels,
            use_bias=False,
            name='theta_backcast_exog'
        )
        self.theta_forecast = layers.Dense(
            basis_channels,
            use_bias=False,
            name='theta_forecast_exog'
        )

    def build(self, input_shape):
        """
        Build the exogenous block and its encoder.

        :param input_shape: Shape of the residual input (y).
        :type input_shape: tuple
        """
        # We need to build the Dense stack from the parent
        # input_shape here refers to the residual input (y)
        super().build(input_shape)

        # Build encoder
        # Input to encoder is (Batch, Time, Exog_Dim)
        total_len = self.backcast_length + self.forecast_length
        if self.use_tcn:
            self.encoder.build((None, total_len, self.exogenous_dim))

    def call(self, inputs, training=None, exogenous_inputs=None):
        """
        Forward pass incorporating exogenous variables.

        Processes the target residual through the dense stack, generates theta
        coefficients, encodes exogenous variables into a dynamic basis via TCN
        (or uses raw exogenous input), and produces backcast/forecast via
        einsum projection.

        :param inputs: Residual target signal of shape
            (batch, backcast_len * input_dim).
        :type inputs: keras.KerasTensor
        :param training: Whether in training mode.
        :type training: bool or None
        :param exogenous_inputs: Tuple of (x_backcast, x_forecast) where
            x_backcast has shape (batch, backcast_len, exog_dim) and
            x_forecast has shape (batch, forecast_len, exog_dim).
        :type exogenous_inputs: tuple
        :return: Tuple of (backcast, forecast) tensors.
        :rtype: tuple[keras.KerasTensor, keras.KerasTensor]

        :raises ValueError: If exogenous_inputs is None.
        """
        if exogenous_inputs is None:
            raise ValueError("ExogenousBlock requires 'exogenous_inputs' passed to call.")

        x_back, x_fore = exogenous_inputs

        # 1. Process Target Residual through Dense Stack (Parent Logic)
        # -----------------------------------------------------------
        # Note: We duplicate the FC stack logic here because the parent .call()
        # calls _generate_backcast immediately, but we need the exogenous basis first.

        x = self.dense1(inputs, training=training)
        if self.use_normalization: x = self.norm1(x)
        x = self.dense2(x, training=training)
        if self.use_normalization: x = self.norm2(x)
        x = self.dense3(x, training=training)
        if self.use_normalization: x = self.norm3(x)
        x = self.dense4(x, training=training)
        if self.use_normalization: x = self.norm4(x)

        # 2. Generate Theta Coefficients (Weights for the Basis)
        # -----------------------------------------------------------
        # Shape: (Batch, Basis_Channels)
        # Note: Unlike standard N-BEATS, these are global weights per sample,
        # not per time-step. They scale the TCN basis vectors.
        theta_b = self.theta_backcast(x, training=training)
        theta_f = self.theta_forecast(x, training=training)

        # 3. Generate Basis from Exogenous Variables
        # -----------------------------------------------------------
        # Concatenate history and future exogenous: (Batch, Total_Len, Exog_Dim)
        x_full = ops.concatenate([x_back, x_fore], axis=1)

        if self.use_tcn:
            # Basis C = TCN(X)
            # Shape: (Batch, Total_Len, TCN_Filters)
            basis_full = self.encoder(x_full, training=training)
        else:
            # Basis = X (Interpretable configuration)
            basis_full = x_full

        # Split basis back into backcast and forecast periods
        basis_b = basis_full[:, :self.backcast_length, :]
        basis_f = basis_full[:, self.backcast_length:, :]

        # 4. Projection (Eq 9)
        # -----------------------------------------------------------
        # Backcast = Basis_b * theta_b
        # basis: (B, T, C), theta: (B, C) -> result: (B, T) (summed over C)
        backcast = ops.einsum('btc,bc->bt', basis_b, theta_b)
        forecast = ops.einsum('btc,bc->bt', basis_f, theta_f)

        # Reshape to flatten (Batch, Time) -> (Batch, Time * 1) if input_dim=1
        backcast = ops.reshape(backcast, (-1, self.backcast_length * 1))
        forecast = ops.reshape(forecast, (-1, self.forecast_length * 1))

        return backcast, forecast

    def _generate_backcast(self, theta):
        """
        Not used; overridden in call.

        :param theta: Unused theta parameters.
        :type theta: keras.KerasTensor
        """
        pass

    def _generate_forecast(self, theta):
        """
        Not used; overridden in call.

        :param theta: Unused theta parameters.
        :type theta: keras.KerasTensor
        """
        pass

    def get_config(self):
        """
        Return configuration dictionary for serialization.

        :return: Configuration dictionary.
        :rtype: dict
        """
        config = super().get_config()
        config.update({
            'exogenous_dim': self.exogenous_dim,
            'tcn_filters': self.tcn_filters,
            'tcn_kernel_size': self.tcn_kernel_size,
            'tcn_dropout': self.tcn_dropout,
            'use_tcn': self.use_tcn
        })
        return config

# ---------------------------------------------------------------------
